### ISSUE TITLE
Please add unpublished game modes if possible.

### ISSUE THREAD

**Issue by Nintendocustom** [OatmealDome/Splatoon-2-Misc-Patches#6]
Is it possible to add unreleased game modes?

**Comment by OatmealDome** [comment]
Rocket and (multiplayer) 8-Ball have been removed from the game in the 4.x series of updates. In addition, it would require several map patches to add support for the gamemodes, which would a) ban you and b) require a layeredfs mod, which is out of scope of this repository.
